Default Config Updated

diff --git a/Deployment/linux/ipop b/Deployment/linux/ipop
--- a/Deployment/linux/ipop
+++ b/Deployment/linux/ipop
@@ -9,7 +9,7 @@ INSTALLATION_DIR=/opt/ipop
 # TODO: Must work eaither with or without /
 
 cat /etc/issue | grep Ubuntu > /dev/null && is_ubuntu=true
-cat /etc/issue | grep CentOS > /dev/null && is_centos=true
+#cat /etc/issue | grep CentOS > /dev/null && is_centos=true
 
 #if [ "$(uname -m)" == "x86_64" ]; then
 #	is_64=true
@@ -18,7 +18,6 @@ cat /etc/issue | grep CentOS > /dev/null && is_centos=true
 #TODO: Check for update
 
 [ -f "$INSTALLATION_DIR" ] || cp $0 "$INSTALLATION_DIR"
-
 
 read -r -d '' GVPN_CONF <<EOT
 {
@@ -48,14 +47,14 @@ read -r -d '' GVPN_CONF <<EOT
         "ip4": "%IP4%",
         "sec": true,
         "multihop": false,
-        "num_successors": 20,
-        "num_chords": 3,
-        "num_on_demand": 2,
-        "num_inbound": 25,
+        "num_successors": 8,
+        "num_chords": 8,
+        "num_on_demand": 20,
+        "num_inbound": 40,
         "ttl_link_initial": 60,
         "ttl_link_pulse": 30,
         "ttl_chord": 180,
-        "ttl_on_demand": 60,
+        "ttl_on_demand": 6000,
         "threshold_on_demand": 128,
         "timer_interval": 1,
         "interval_management": 15,
@@ -207,19 +206,18 @@ case "$action" in
 		mkdir -p "$INSTALLATION_DIR" 2>/dev/null
 		cd "$INSTALLATION_DIR"
 
-
 		if [ "$is_ubuntu" = true ]; then
 			if ! (apt-get update && apt-get install -y psmisc wget ca-certificates python) ; then
 				echo "$MSG_INSTALL_INSTALLATION_FAILED"
 				exit 4
 			fi
 		fi
-		if [ "$is_centos" = true ]; then
-			if ! (yum update && yum install -y psmisc wget ca-certificates python) ; then
-				echo "$MSG_INSTALL_INSTALLATION_FAILED"
-				exit 4
-			fi
-		fi
+#		if [ "$is_centos" = true ]; then
+#			if ! (yum update && yum install -y psmisc wget ca-certificates python) ; then
+#				echo "$MSG_INSTALL_INSTALLATION_FAILED"
+#				exit 4
+#			fi
+#		fi
 
 		wget -O "$CONTROLLER_BINARY_NAME" "$CONTROLLER_BINARY_URL" && tar xvzf "$CONTROLLER_BINARY_NAME"
 #		if [ "$(md5sum $CONTROLLER_BINARY_NAME | awk '{print $1}')" == "$CONTROLLER_BINARY_MD5" ]; then
@@ -282,14 +280,14 @@ case "$action" in
 
 	start)
 		force_root
-		cd "$INSTALLATION_DIR"
+		cd "$INSTALLATION_DIR/$CONTROLLER_DIR"
 		[ -d log ] || mkdir log
 #		if [ $is_64 ]; then
 #			sh -c './ipop-tincan-x86_64 1> log/out.log 2> log/err.log &'
 #		else
 		sh -c './ipop-tincan 1> log/out.log 2> log/err.log &'
 #		fi
-		cd "$CONTROLLER_DIR"/controller
+		cd controller
 		python -m Controller -c ../conf/config.json &> ../log/log.txt &
 
 		echo "$MSG_START_SUCCESS"
